apiVersion: apps/v1
kind: Deployment # Declared as 'deployment' kind - provides declarative updates for pods and replicasets
metadata:
  name: infinity101-k8s-apiservice # Given a name and a label of 'apiservice'
  labels:
    app: api
spec:
  replicas: 3 # requesting 3 replicates matching on the app label set to 'api'
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers: # container to launch backend api
      - name: api
        image: 240343621469.dkr.ecr.eu-west-1.amazonaws.com/101-eks-api:latest
        ports:
        - containerPort: 80